# Generated by Django 4.1 on 2023-02-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="scope",
            field=models.CharField(default="Group Project", max_length=50),
            preserve_default=False,
        ),
    ]
