# Generated by Django 4.1 on 2023-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
