# Generated by Django 4.1 on 2023-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_project_main_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(
                default="During the summer holidays I discovered Midjourney which is an AI that is able to create amazing art through text promts given to it. After experimenting with it for a bit, I feel in love with it and decided that I wanted to share my art to a Twitter account. To make this process easier I made a discord bot that does most of the work, and all I needed to do was create the art."
            ),
            preserve_default=False,
        ),
    ]
