# Generated by Django 4.1 on 2023-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_img_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="roles_list",
            field=models.TextField(null=True),
        ),
    ]
