# Generated by Django 4.1 on 2023-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_project_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="link_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
